sequenceDiagram

participant User
participant Library
participant Book

User->>Library: create_loan(book, user, start_date, end_date)
Library->>Book: mark_as_unavailable()

create participant Loan

Library->>Loan: create_loan(book, user, start_date, end_date)

Library-->>User: loan created
